export const SERVER_DIR = 'http://localhost:3001/';
export const TYPES = 'types';
export const GET_DIETS = 'GET_DIETS';
export const POST_RECIPE = 'recipe';
export const SET_RECIPE = 'SET_RECIPE';
export const RECIPES = 'recipes';//get recipes backend
export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE = 'GET_RECIPE';
export const RECIPES_PER_PAGE = 9;
export const FILTER_DIET = 'FILTER_DIET';
export const SORT_NAME = 'SORT_NAME';